import React from 'react';
import { Link } from 'react-router-dom';
import './ResultDetails2.css';

function ResultDetails2() {
  return (
    <div className="result-container">
      <h2 className="result-title">Xamify Result Process</h2>

      <div className="result-step">
        <h3>📘 Teacher Adds Marks</h3>
        <p>After conducting the exam, the teacher enters and submits the marks for each student in the portal.</p>
      </div>

      <div className="result-step">
        <h3>📤 Submission to Admin</h3>
        <p>Once the teacher has entered the marks, they submit the results to the admin for approval and verification.</p>
      </div>

      <div className="result-step">
        <h3>✅ Admin Verification</h3>
        <p>The admin reviews the marks submitted by the teacher, ensures accuracy, and approves them.</p>
      </div>

      <div className="result-step">
        <h3>📊 Graph Generation</h3>
        <p>After approval, performance graphs and analytics are automatically generated by the system.</p>
      </div>

      <div className="result-step">
        <h3>🔍 Performance Insights</h3>
        <p>Admins analyze student performance using visual graphs like bar charts, pie charts, and line graphs.</p>
      </div>

      {/* ✨ Unique Button to Navigate */}
      <div className="navigate-button-container">
        <Link to="/userresult" className="navigate-button">
          🔗  Go To Student Marks Page 
        </Link>
      </div>
    </div>
  );
}

export default ResultDetails2;
